### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by AndxEng** [Iterable/iterable-android-sdk#115]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
        at com.iterable.iterableapi.IterableActivityMonitor$2.onActivityPaused(IterableActivityMonitor.java:68)
        at android.app.Application.dispatchActivityPaused(Application.java:234)
        at android.app.Activity.onPause(Activity.java:1664)

**Comment by vbabenkoru** [comment]
@AndxEng Thank you for the report! We'll fix this and release an update shortly. Do you have any context on when this is happening and what triggers this?

**Comment by vbabenkoru** [comment]
@AndxEng We've released version 3.1.1 with a fix for this issue. Thanks!
