### ISSUE TITLE
Warning log using string resource as iterable_notification_channel_name: expected String

### ISSUE THREAD

**Issue by friederikewild** [Iterable/iterable-android-sdk#235]
Small request - nothing seems broken, but the warning log sounds alarming and might be confusing to others.

We are using a string resource to provide the channel name per [documentation](https://support.iterable.com/hc/en-us/articles/115000331943-Setting-up-Android-Push-Notifications-). Not sure why it needs to print a warning when afterwards it actually works and logs the correct resolved string as well as showing it in the app settings.

Manifest:
```
 <application
        ...>
        <meta-data
            android:name="iterable_notification_channel_name"
            android:resource="@string/notification_channel_name" />
```

strings:
```
<string name="notification_channel_name">All notifications</string>
```

Warning logs as well as iterable happy log:

```
W/Bundle: Key iterable_notification_channel_name expected String but value was a java.lang.Integer.  The default value <null> was returned.
W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:1163)
        at com.iterable.iterableapi.IterableNotificationHelper$IterableNotificationHelperImpl.getChannelName(IterableNotificationHelper.java:279)
        at com.iterable.iterableapi.IterableNotificationHelper$IterableNotificationHelperImpl.createNotification(IterableNotificationHelper.java:101)
        at com.iterable.iterableapi.IterableNotificationHelper.createNotification(IterableNotificationHelper.java:36)
        at com.iterable.iterableapi.IterableFirebaseMessagingService.handleMessageReceived(IterableFirebaseMessagingService.java:60)
        at com.iterable.iterableapi.IterableFirebaseMessagingService.onMessageReceived(IterableFirebaseMessagingService.java:20)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.0:78)
        at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.0:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:919)
D/IterableNotification:  💚 channel name: All notifications
D/IterableNotification:  💚 Creating notification: channelId = xxx channelName = All notifications channelDescription = 
```

Currently on Iterable version '3.2.2'

**Comment by Ayyanchira** [comment]
Hi @friederikewild! 
By default, the Iterable's log level is set to ERROR. It can be set to different Log Level when initializing the config. Can you confirm if the Log level is not set to VERBOSE/ INFO/ DEBUG?

**Comment by friederikewild** [comment]
Hi @Ayyanchira Thanks for your message. 
Sorry, didn't get back to checking earlier. I can confirm that I had indeed set it to `VERBOSE`. Since the error was printed with log level `"WARNING"`, I didn't think it would make a difference which config I have.

I know tested it without setting anything - in this case I can confirm, that I no longer see the above warning. However, I still get some logs with tag `V/Iterable Call:` from the `IterableInAppManager` - which also seems wrong, given that you stated that the default should only log errors?

But as to my original issue, feel free to close it as it seems to just be a confusing log level

**Comment by Ayyanchira** [comment]
I'm glad it helped and there are no warning logs being displayed. :) 
I will take a look on `V/Iterable Call:` and update it here.
