### ISSUE TITLE
Crash: IterableInAppFragmentHTMLNotification.java line 242 NullPointerException

### ISSUE THREAD

**Issue by EJohnsonAtPeaksware** [Iterable/iterable-android-sdk#241]
Hello! We're receiving this crash from version 3.2.3 via our Firebase Crashlytics.  Any ideas? Perhaps it just needs a null-guard somewhere?

Let me know if I can provide more information.  We've seen 246 crashes for this in the past 24h, so it's a higher severity for our TrainingPeaks app.

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'void com.iterable.iterableapi.IterableHelper$IterableUrlCallback.execute(android.net.Uri)' on a null object reference
com.iterable.iterableapi.IterableInAppFragmentHTMLNotification.onUrlClicked
```

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.iterable.iterableapi.IterableHelper$IterableUrlCallback.execute(android.net.Uri)' on a null object reference
       at com.iterable.iterableapi.IterableInAppFragmentHTMLNotification.onUrlClicked(IterableInAppFragmentHTMLNotification.java:242)
       at com.iterable.iterableapi.IterableWebViewClient.shouldOverrideUrlLoading(IterableWebViewClient.java:27)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle.apk-stable-410410683:16)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:197)
       at android.app.ActivityThread.main(ActivityThread.java:8019)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by EJohnsonAtPeaksware** [comment]
There's a second, and possibly related crash.
```
IterableInAppFragmentHTMLNotification.java line 278
```

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
com.iterable.iterableapi.IterableInAppFragmentHTMLNotification$5.run
```

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at com.iterable.iterableapi.IterableInAppFragmentHTMLNotification$5.run(IterableInAppFragmentHTMLNotification.java:278)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by vbabenkoru** [comment]
Thank you for the report. We've prepared a fix for this.

**Comment by EJohnsonAtPeaksware** [comment]
Could we get this tagged for a release 3.2.5?
