### ISSUE TITLE
Resolve String / Resource ID For Channel Name

### ISSUE THREAD

**Issue by searchy2** [Iterable/iterable-android-sdk#250]
Iterable currently does not resolve the channel name correctly from the Manifest file. It expects a direct string when the value could be a resource ID. 

The following error is thrown.

```
Bundle: Key iterable_notification_channel_name expected String but value was a java.lang.Integer.  The default value <null> was returned.
Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:1168)
        at com.iterable.iterableapi.IterableNotificationHelper$IterableNotificationHelperImpl.getChannelName(IterableNotificationHelper.java:279)
        at com.iterable.iterableapi.IterableNotificationHelper$IterableNotificationHelperImpl.createNotification(IterableNotificationHelper.java:101)
        at com.iterable.iterableapi.IterableNotificationHelper.createNotification(IterableNotificationHelper.java:36)
        at com.iterable.iterableapi.IterableFirebaseMessagingService.handleMessageReceived(IterableFirebaseMessagingService.java:60)
        at com.treatmyocd.nocd.service.NocdFirebaseMessagingService.onMessageReceived(NocdFirebaseMessagingService.kt:72)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.2.1:80)
        at com.google.firebase.messaging.zzh.run(com.google.firebase:firebase-messaging@@20.2.1:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:919)

```
The error is in the `getChannelName` method in `IterableNotificationHelper`. 

![MaxthonSnap20200717124105](https://user-images.githubusercontent.com/19896174/87815257-e8e93280-c82a-11ea-954a-b6f621527d40.png)

Thankfully, the exception is caught in the try/catch.

**Comment by vbabenkoru** [comment]
@searchy2 Thank you for the report! We'll fix it in one of the next releases.

**Comment by vbabenkoru** [comment]
@searchy2 I could not reproduce this. `getString` still returns a string even if I use a string resource. How do you define it in `AndroidManifest.xml`?

**Comment by searchy2** [comment]
Thank you for taking a look! It's used as a string resource `@string/notification_updates`.

**Comment by vbabenkoru** [comment]
@searchy2 That log entry is a warning, it works fine otherwise.

**Comment by searchy2** [comment]
It's being caught by an outside try/catch when it should be caught by the library try / catch. If there was no outside try / catch, the app would crash.

**Comment by virusman** [comment]
getString itself is catching the exception and logging it, proceeding to return null. Our exception handler does not get called.

**Comment by vbabenkoru** [comment]
I've prepared a PR to refactor this a bit and get rid of the warning.
