### ISSUE TITLE
Exception on SDK 3.2.5 

### ISSUE THREAD

**Issue by rpadma** [Iterable/iterable-android-sdk#273]
I see this exception in the log trace when the app starts. I'm using the SDK version 3.2.5 `com.iterable:iterableapi:3.2.5`. Is this is a known issue or how to get rid of this exception on the app start? 

 ```
   Exception occurred for : https://api.iterable.com/api/events/inAppConsume
2020-10-21 11:33:33.520 16977-17403/com.whoop.android.dev.qa E/IterableRequest:  ❤️ timeout
    java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:225)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:317)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:311)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:207)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:395)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:146)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:900)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:772)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:493)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:429)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:560)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.iterable.iterableapi.IterableRequest.doInBackground(IterableRequest.java:123)
        at com.iterable.iterableapi.IterableRequest.doInBackground(IterableRequest.java:26)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.net.SocketTimeoutException: Read timed out
        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
        at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:583)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:145)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:317) 
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:311) 
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:207) 
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:395) 
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:146) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:900) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:772) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:493) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:429) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:560) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30) 
        at com.iterable.iterableapi.IterableRequest.doInBackground(IterableRequest.java:123) 
        at com.iterable.iterableapi.IterableRequest.doInBackground(IterableRequest.java:26) 
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

```

**Comment by vbabenkoru** [comment]
@rpadma Looks like a network timeout issue. The device probably doesn't have internet connection. The log entry is from our Iterable SDK logger, that indicates that the exception was caught and printed to log.
