### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by mondoktamas** [Iterable/iterable-android-sdk#281]
Hey! I'm getting the below exception using your latest lib version.

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:2)
       at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:12)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:17)
       at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:1)
       at com.iterable.iterableapi.IterableInAppFragmentHTMLNotification.access$601(IterableInAppFragmentHTMLNotification.java:1)
       at com.iterable.iterableapi.IterableInAppFragmentHTMLNotification$5.run(IterableInAppFragmentHTMLNotification.java:1)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
       at android.view.Choreographer.doCallbacks(Choreographer.java:875)
       at android.view.Choreographer.doFrame(Choreographer.java:772)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8347)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

Seems to me like the SDK tries to show the InApp fragment dialog after the app moved to the background and the onSaveInstanceState called.

**Comment by vbabenkoru** [comment]
@mondoktamas Thank you for the report! We'll look into it and release a fix.
