### ISSUE TITLE
Encryption of Customer Data

### ISSUE THREAD

**Issue by fabiopires** [Iterable/iterable-android-sdk#330]
Hi,

We are using Iterable SDK for Android in one of our mobile apps and we noticed that customer data (such as the email address, and auth tokens) are being stored unencrypted, inside app's shared preferences.

Is it possible to implement a mechanism to leave this data encrypted when at rest, and decrypt it when in runtime?

Reference: https://github.com/Iterable/iterable-android-sdk/blob/1402e45e7e57cc21915beed35588ebd81ada1627/iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java#L1037

Thank you.

**Comment by UMFsimke** [comment]
Hey team, due to the HIPAA compliancy this is **a must** and we would like to tackle it. Do you have some suggestion how would you like it to be done? Should we add [EncryptedSharedPreferences](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences), the only thing I'm worried about this approach is that it has bugs and sometimes Keystore operations might fail and preferences won't be usable. Maybe it would be a good approach to first create a singleton(s), like `SessionDataStore`, and move the CRUD logic there and then encrypt sensitive values before storing them in shared prefs, while developers would be responsible to pass secret and manage it?

**Comment by roninopf** [comment]
Hi @fabiopires, @UMFsimke, we just released Android SDK 3.4.10 which has enhanced privacy around the email and user ID as you've pointed out; I'll be closing this now, but please feel free to reach out (a CSM ticket would be best, regarding this topic), if you have a new issue to let us know about. Thanks!

**Comment by PaulWoitaschek** [comment]
This is causing problems with the Android Backups:

>                    Caused by: com.google.crypto.tink.shaded.protobuf.a0: Protocol message contained an invalid tag (zero).
                                                             	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.I(SourceFile:76)
                                                             	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.F(SourceFile:3)
                                                             	at com.google.crypto.tink.proto.a.V(Unknown Source:2)
                                                             	at bc.d.read(Unknown Source:8)
                                                             	at com.google.crypto.tink.a.a(Unknown Source:0)
                                                             	at bc.a$b.e(SourceFile:21)
                                                             	at bc.a$b.f(SourceFile:1)
                                                             	at bc.a$b.d(SourceFile:12)
                                                             	at androidx.security.crypto.EncryptedSharedPreferences.a(SourceFile:47)
                                                             	at com.iterable.iterableapi.a0.<init>(SourceFile:

It would be great if you could catch these crashes and nuke the iterable config as there is nothing actionable to do at that point.
