### ISSUE TITLE
Getting warning for https://api.iterable.com/api/inApp/getMessages (status code: 429) when initializing Iterable SDK 

### ISSUE THREAD

**Issue by raj-rupakheti** [Iterable/iterable-android-sdk#347]
Hi,

When I tried to initialize Iterable SDK for Android app, getting **https://api.iterable.com/api/inApp/getMessages** (**status code: 429**)  error.  (error message response => `Rate limit exceeded. Please try again later.`  from Class: `IterableRequest` , Line 143 , `requestResult = response.toString()`;) 
Iterable SDK version : **3.2.9** 

But if I do use another Iterable Mobile API key , then no issue. Can you guys please let me know , In what scenario we do get this issue. When we created API keys, we followed same steps and both API keys are Mobile type .  One API key has no issue while initialing and other has warning/ issue. 

**Note:** Functionality (Push message, deep link on push message) are working perfectly  for that  same API key which will occur error on initialize.  I have added Stack-trace error below . 

E/IterableRequest:  ❤️ <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    Exception occurred for : https://api.iterable.com/api/inApp/getMessages
E/IterableRequest:  ❤️ Value Rate of type java.lang.String cannot be converted to JSONObject
    org.json.JSONException: Value Rate of type java.lang.String cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:111)
        at org.json.JSONObject.<init>(JSONObject.java:163)
        at org.json.JSONObject.<init>(JSONObject.java:176)
        at com.iterable.iterableapi.IterableRequest.doInBackground(IterableRequest.java:154)
        at com.iterable.iterableapi.IterableRequest.doInBackground(IterableRequest.java:26)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by roninopf** [comment]
Hi @raj-rupakheti, is this still an open issue? If it is, you should open a ticket with your CSM, since 429s are related to rate limiting of `getMessages`. It's likely to be an issue originating from the backend.

**Comment by raj-rupakheti** [comment]
@roninopf yep, it's still issue. But we already spoke with Iterable support team on slack. For now, We can ignore it. Since We can't disable from Iterable SDK on current version. But in-future version,  we will able to disable. So, we are ignoring it and keep chatting with Iterable support team on slack channel. thanks

**Comment by roninopf** [comment]
Thanks! I'll be closing this specific GitHub issue, then, since it's not specific to the Android SDK.
