### ISSUE TITLE
IterableInAppFragmentHTMLNotification NullPointerException

### ISSUE THREAD

**Issue by imondok** [Iterable/iterable-android-sdk#378]
Hi!
We have multiple crash logs  reported by firebase crash analytics on android. Iterable SDK v.3.2.9

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:149)
at com.iterable.iterableapi.IterableInAppFragmentHTMLNotification.hideWebView(IterableInAppFragmentHTMLNotification.java:375)
at com.iterable.iterableapi.IterableInAppFragmentHTMLNotification.onUrlClicked(IterableInAppFragmentHTMLNotification.java:256)
at com.iterable.iterableapi.IterableWebViewClient.shouldOverrideUrlLoading(IterableWebViewClient.java:26)
at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle.aab-stable-443021033:14)
at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:174)
at android.app.ActivityThread.main(ActivityThread.java:7711)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by Ayyanchira** [comment]
Thanks for writing in @imondok!

This seems like a crash we previously encountered when an inapp tries to animate when dismissing. 
We've added a fix for it in Version [3.2.11](https://github.com/Iterable/iterable-android-sdk/releases/tag/3.2.11).

I will recommend trying out SDK version >= 3.2.11

Let us know if the issue persists.
