### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unable to start receiver com.iterable.iterableapi.IterablePushActionReceiver

### ISSUE THREAD

**Issue by sidcpatel** [Iterable/iterable-android-sdk#392]
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.iterable.iterableapi.IterablePushActionReceiver: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.vizmanga.android (pid=26229, uid=10218) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4321)
       at android.app.ActivityThread.access$1600(ActivityThread.java:247)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Issue shows up for Apps targeting Android 12 and running on Android 12 devices. Issue occurs when push notifications are received by the app.

Related documentation from Android.

https://developer.android.com/about/versions/12/behavior-changes-all#close-system-dialogs

Possible Fix

`Note: If your app targets Android 12, you don't need to use ACTION_CLOSE_SYSTEM_DIALOGS in this situation. That's because, if your app calls startActivity() while a window is on top of the notification drawer, the system closes the notification drawer automatically.`

**Comment by vbabenkoru** [comment]
Closed via #394.
