### ISSUE TITLE
NPE on  com.iterable.iterableapi.IterableActivityMonitor$2.onActivityResumed (IterableActivityMonitor.java:62) 

### ISSUE THREAD

**Issue by ravisaini1990** [Iterable/iterable-android-sdk#405]
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
com.iterable.iterableapi.IterableActivityMonitor$2.onActivityResumed (IterableActivityMonitor.java:62)

**Comment by roninopf** [comment]
@ravisaini1990 Can you file a ticket with your CSM with more specifics? I'm thinking there maybe a lot more details that are specific to this NPE.

**Comment by ravisaini1990** [comment]
Observed on Android 9 and above
32% on Google and 29% on Samsung device and 13% on Motorola 

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
       at com.iterable.iterableapi.IterableActivityMonitor$2.onActivityResumed(IterableActivityMonitor.java:62)
       at android.app.Application.dispatchActivityResumed(Application.java:416)
       at android.app.Activity.dispatchActivityResumed(Activity.java:1397)
       at android.app.Activity.onResume(Activity.java:1950)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:434)
       at com.stitcherx.app.application.ui.MainActivity.onResume(MainActivity.kt:238)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1476)
       at android.app.Activity.performResume(Activity.java:8191)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4751)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by ravisaini1990** [comment]
29% Android 10
29% Android 11
26% Android 12
16% Android 9

**Comment by Ayyanchira** [comment]
Hi @ravisaini1990 , 
What is your use case/ What functionality are you trying to accomplish?
and also, which version of SDK is being used?

**Comment by vbabenkoru** [comment]
@ravisaini1990 Thank you for reporting this issue. Please contact Iterable Support. Looking at the code, there isn't any case where this element may be null. I suspect there may be an issue with ProGuard/DexGuard or a similar obfuscator/optimizer. Unfortunately, we can't help with specifics of a customer's app in Github issues. Please open a Support ticket, and it'll be escalated to Iterable Engineering, and we'll help you with this. Thank you.

**Comment by ravisaini1990** [comment]
@roninopf @vbabenkoru @Ayyanchira
Following error I received- 
 /IterableApi:  ❤️ Error while persisting email/userId
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
        at com.iterable.iterableapi.IterableApi.getPreferences(IterableApi.java:1222)
        at com.iterable.iterableapi.IterableApi.storeEmailAndUserId(IterableApi.java:1310)
        at com.iterable.iterableapi.IterableApi.setUserId(IterableApi.java:298)
