### ISSUE TITLE
Crash when click on Push Notification

### ISSUE THREAD

**Issue by c-karolpawlik** [Iterable/iterable-android-sdk#423]
Hi,

I faced an issue with one thing in your library. I'm using yours default Push handler. And on Android 12 when i click on the notification i received my app crashes.
I'm receiving Push notifications with default handler embedded in library.

The exception i got:
```
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.iterable.iterableapi.IterablePushActionReceiver: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.my.app.test (p
id=5319, uid=10146) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.`

       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4321)
       at android.app.ActivityThread.access$1600(ActivityThread.java:247)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)


Caused by java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.my.app.test  (pid=5319, uid=10146) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
       at android.os.Parcel.createException(Parcel.java:2409)
       at android.os.Parcel.readException(Parcel.java:2392)
       at android.os.Parcel.readException(Parcel.java:2334)
       at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5665)
       at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1177)
       at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
       at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
       at com.iterable.iterableapi.IterablePushActionReceiver.onReceive(IterablePushActionReceiver.java:32)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4312)
       at android.app.ActivityThread.access$1600(ActivityThread.java:247)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:2955)
	at com.android.server.wm.ActivityTaskManagerService.access$900(ActivityTaskManagerService.java:294)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:5309)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13183)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:12752)

```
I'm using you SDK as a part of [mParticle Iterable integration]( https://github.com/mparticle-integrations/mparticle-android-integration-iterable) and I'm using 3.3.9 version of your library.

Is it known issue? is it fixed in some newer version?

**Comment by davidtruong** [comment]
@c-karolpawlik Can you try upgrading to the latest version of the android SDK. This looks related to a fix that we have already put out.

I'll close out the ticket, but if you have any additional questions feel free to open up a new issue.

**Comment by hytea** [comment]
@davidtruong could you push the relevant changes to the react-native SDK? I am on the latest version 1.1.3 of that SDK and I am getting this error on android devices.

**Comment by hytea** [comment]
@roninopf This is better addressed as an issue for the react-native SDK vs commenting on a closed issue. Forgive me. Here is the new issue. https://github.com/Iterable/react-native-sdk/issues/300
