### ISSUE TITLE
IterableInAppManager.java line 330 com.iterable.iterableapi.IterableInAppManager.syncWithRemoteQueue

### ISSUE THREAD

**Issue by ravisaini1990** [Iterable/iterable-android-sdk#485]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.iterable.iterableapi.IterableInAppMessage.isRead()' on a null object reference
       at com.iterable.iterableapi.IterableInAppManager.syncWithRemoteQueue(IterableInAppManager.java:330)
       at com.iterable.iterableapi.IterableInAppManager.access$000(IterableInAppManager.java:32)
       at com.iterable.iterableapi.IterableInAppManager$1.execute(IterableInAppManager.java:178)
       at com.iterable.iterableapi.IterableRequestTask.onPostExecute(IterableRequestTask.java:296)
       at com.iterable.iterableapi.IterableRequestTask.onPostExecute(IterableRequestTask.java:28)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.-wrap1()
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6797)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)

Other Statistics of Crash From Firebase- 

Crash on Android Versions - 
50% Android 8
30% Android 9
10% Android 11
10% Android 13
-----
Crash on Devices - 
50% motorola
30% samsung
10% Sony
10% OnePlus
-----------------
60% In background
0% Rooted
100% Proximity on

**Comment by joaodordio** [comment]
Hey @ravisaini1990 are you able to share more context on the issue you are having please?
