### ISSUE TITLE
NullPointerException in IterablePushActionReceiver

### ISSUE THREAD

**Issue by orcunozyurt** [Iterable/iterable-android-sdk#56]
When we click on the notification, If the app is closed, we get crash. 

- Both 3.0.0 & 3.0.1 versions of SDK

- Android 7.0 & 8.0 & 8.1

- When the app is on background, It works fine. We can navigate to the app. However, If the app is not on background(closed) the app crashes when notification clicked. 

```
java.lang.RuntimeException: Unable to start receiver com.iterable.iterableapi.IterablePushActionReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
        at com.iterable.iterableapi.IterableApi.getPreferences(IterableApi.java:1193)
        at com.iterable.iterableapi.IterableApi.setAttributionInfo(IterableApi.java:115)
        at com.iterable.iterableapi.IterableApi.setNotificationData(IterableApi.java:172)
        at com.iterable.iterableapi.IterablePushActionReceiver.handlePushAction(IterablePushActionReceiver.java:84)
        at com.iterable.iterableapi.IterablePushActionReceiver.onReceive(IterablePushActionReceiver.java:39)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
```
Any help would be appreciated.

**Comment by vbabenkoru** [comment]
Thanks for the report! This looks like a bug in the SDK; we'll investigate and release a fix for that.

**Comment by vbabenkoru** [comment]
@orcunozyurt Are you initializing the SDK in your `Application` `onCreate`?

**Comment by serenasoldo** [comment]
@vbabenkoru any idea about when you'll release an update with this fix? Looking forward for it :)

**Comment by serenasoldo** [comment]
@vbabenkoru thanks for your message.

The problem we are experiencing is only on the first launch of the app. 
We can't initialise the Iterable sdk on the Application's onCreate because we offer the app in multiple countries and we have set up multiple Iterable projects (one for each country) so we can't know the Iterable key to use for the initialisation until the customer selects a country and logs in.
At that point, if the customer receives a push notification and taps on it, the app will crash.

At the next restart of the app, since we already know the country of the user, we can initialise Iterable in the Application's onCreate and from then on everything goes fine. 

If you have a workaround for us to initialise Iterable sdk in the Application's onCreate without providing the iterable key (and adding the iterable key only after the login) we'd be happy to implement it.
But for now, it would be nice if we can at least avoid the crash, that's why we are so looking forward for the next release :)

**Comment by vbabenkoru** [comment]
@serenasoldo Thanks for the explanation!
But how does the app receive the push message if it was never opened? The app has to register the device token at least once since app install for a push message to get sent (and it needs an API key and user email for that).

**Comment by serenasoldo** [comment]
Sorry, probably I wasn't clear describing the use case. I'll list here the steps, maybe it's easier.
This is what happens right now (with sdk version 3.0.1):
- The user installs the app
- The user launches the app
- Since we don't know the user's country yet, we can't initialise iterable in the Application's onCreate
- The user logs in
- Now we know the user's country so we can initialise Iterable and register the user for push notification
- The user closes the app and goes back to their life
- Few hours later the user receives a push notification
- The user taps on it
- The app crashes 

At this point:
- The user starts the app for the second time
- We know the user's country now so we can initialise Iterable already in the Application's onCreate
- From now on, any received push notification won't cause any crash.

Does that explains the use case a bit more clearly?

**Comment by serenasoldo** [comment]
@vbabenkoru any update on when the next release will go live?

**Comment by vbabenkoru** [comment]
@orcunozyurt @serenasoldo Version 3.0.2 has been released!
This will fix the crashes, but we strongly recommend initializing in `Application#onCreate` whenever possible to make sure push opens are tracked.

**Comment by serenasoldo** [comment]
@vbabenkoru thanks a lot! :)
